# Generated by Django 5.2.6 on 2026-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_accesslog_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('EXAMINATION', 'Examination'), ('REGISTRATION', 'Registration'), ('MAINTENANCE', 'Maintenance'), ('EVENT', 'Event')], default='ACADEMIC', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='notices/files/')),
                ('is_latest', models.BooleanField(default=True, help_text="Show in the 'Latest' ticker")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
