# Generated by Django 5.2.6 on 2026-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
