# Generated by Django 5.2.6 on 2026-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal comments only', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_reg_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Birth Reg Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_nid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Father's NID"),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_1st_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_2nd_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_3rd_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_4th_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_5th_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_6th_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa_7th_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_nid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Mother's NID"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text='Full Name of the Student', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_po',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_upazila',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_village_house_road',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village/House/Road'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_po',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_upazila',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_village_house_road',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village/House/Road'),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Board Registration Number', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, help_text='Board Roll Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='testimonial_withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='Academic Session (e.g., 2021-22)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default='1st', max_length=10),
        ),
    ]
