# Generated by Django 5.2.6 on 2026-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_student_cgpa_remove_student_guardian_name_and_more'),
    ]

    operations = [
    ]
