# Generated by Django 5.2.6 on 2026-04-05 18:16

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_student_name_alter_student_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=myapp.models.generate_student_id, max_length=20, unique=True),
        ),
    ]
