# Generated by Django 5.2.6 on 2026-04-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_guardian_name_student_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
